### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by sblinz-zz** [Idnan/inline-style#5]
Hi,

This is great but I could not get it to work. I tried including the min and regular js but attaching classes in your format didn't affect styling in Chrome or Firefox.

Maybe I'm missing something?

**Comment by kamranahmedse** [comment]
Did you add ’Furnish.apply()’? Will you

**Comment by nilbuild** [comment]
@sblinstein It seems to be working fine:

https://jsfiddle.net/jqhmfgb2/1/

Did you add `Furnish.apply()`? Could you possibly create a fiddle?

**Comment by sblinz-zz** [comment]
Ah, I missed that in the README, figured I was doing something stupid. Works great! Thank you for making this!
