### ISSUE TITLE
This is a bad idea. Do not encourage people to use this.

### ISSUE THREAD

**Issue by Amberlamps** [Idnan/inline-style#7]
I know that this is opinion-based, but I would like to provide a little list of arguments on why this module is a bad idea. It is okay for experimenting, but please do not use this in production.
- `MutationObserver` used in this module is not supported by older browsers and there is no backwards-compatibility implemented.
- Instead of changing rules in your CSS file, you are now changing class names in HTML elements. What is the benefit of that? It is the same work.
- This is basically inline css. Let's say you want to update padding from `p10` to `p15`. You have to update every element individually, because there is no external stylesheet anymore.
- By default this module inspecting and observing every DOM node. Browsers already do that by default. Why the extra work?
- It absolutely does not fit in modern development workflows (CSS preprocessors + watch + livereload).

**Comment by Idnan** [comment]
Well the idea is not to encourage people to use this. My only purpose was to create something interesting from `MutationObserver`. That we can build things like this.
